security:
  oauth2:
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: https://graph.facebook.com/v13.0/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/v13.0/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
